// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcybA09jNszkpKV7q5KftdGwYt6sC62w',
    appId: '1:305900117470:web:accb726c9af5d5c17c114f',
    messagingSenderId: '305900117470',
    projectId: 'sop-architecture',
    authDomain: 'sop-architecture.firebaseapp.com',
    storageBucket: 'sop-architecture.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_NFVxjLQdiYyQ56idU0A-ACRY1VBW7Y',
    appId: '1:305900117470:android:4b45d278d67069077c114f',
    messagingSenderId: '305900117470',
    projectId: 'sop-architecture',
    storageBucket: 'sop-architecture.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTXn4lLqDGe-g-IpYt7nI5HOeYx4fhZxM',
    appId: '1:305900117470:ios:507f2e4df17e69f67c114f',
    messagingSenderId: '305900117470',
    projectId: 'sop-architecture',
    storageBucket: 'sop-architecture.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTXn4lLqDGe-g-IpYt7nI5HOeYx4fhZxM',
    appId: '1:305900117470:ios:507f2e4df17e69f67c114f',
    messagingSenderId: '305900117470',
    projectId: 'sop-architecture',
    storageBucket: 'sop-architecture.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcybA09jNszkpKV7q5KftdGwYt6sC62w',
    appId: '1:305900117470:web:11745bbbb17a71f07c114f',
    messagingSenderId: '305900117470',
    projectId: 'sop-architecture',
    authDomain: 'sop-architecture.firebaseapp.com',
    storageBucket: 'sop-architecture.appspot.com',
  );
}
